// Gobal get node variables
const recipeList = () => document.querySelector("#recipe-list")
const titleInput = () => document.querySelector("#title-input")
const shortDescriptionInput = () => document.querySelector("#short-description-input")
const ingredientsInput = () => document.querySelector("#ingredients-input")
const instructionsInput = () => document.querySelector("#instructions-input-list")
const instructionsInputList = () => document.querySelectorAll("#instructions-input-list textarea")
const authorInput = () => document.querySelector("#author-input")
const recipeForm = () => document.querySelector("#recipe-form")
const addStepButton = () => document.querySelector("#addStepButton")
const viewAllRecipes = () => document.querySelector("#view-all")
const searchButton = () => document.querySelector("#search-button")
const keySearchSelector = () => document.querySelector("#key-search")
const searchInput = () => document.querySelector("#search-input")